/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ComponentType: typeof import("preact").ComponentType
  const Fragment: typeof import('preact').Fragment
  const FunctionalComponent: typeof import("preact").FunctionalComponent
  const If: typeof import('@/utils/if').If
  const RouteLink: typeof import('@/router').RouteLink
  const VNode: typeof import("preact").VNode
  const createContext: typeof import('preact').createContext
  const createRef: typeof import('preact').createRef
  const h: typeof import('preact').h
  const useCallback: typeof import('preact/hooks').useCallback
  const useContext: typeof import('preact/hooks').useContext
  const useEffect: typeof import('preact/hooks').useEffect
  const useMemo: typeof import('preact/hooks').useMemo
  const useReducer: typeof import('@/utils/TypedUseState').useReducer
  const useRef: typeof import('preact/hooks').useRef
  const useRoute: typeof import('@/router').useRoute
  const useRouter: typeof import('@/router').useRouter
  const useState: typeof import('@/utils/TypedUseState').useState
}
